version: '3'
services:
  pentaho:
    container_name: pentaho
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./data/hsqldb:/opt/pentaho/server/pentaho-server/data/hsqldb
      - ./data/repository:/opt/pentaho/server/pentaho-server/pentaho-solutions/system/jackrabbit/repository
    entrypoint:
      - sh
      - 'entrypoint.sh'

# # Data volumes
# volumes:
#   pentaho-hsqldb-data:
